docs: clarify replace operation
ipfs/pinning-services-api-spec pull request #61
Opened 2020-09-09 17:50 UTC by lidel

This PR updates docs and renames "modify" operation with "replace":

- "update" and "modify" do not describe what is actually happening.
- "replace" should make it easier to reason about the purpose of this operation.

Preview: https://ipfs.github.io/pinning-services-api-spec/#specUrl=https://raw.githubusercontent.com/ipfs/pinning-services-api-spec/docs/replace-call/ipfs-pinning-service.yaml

2020-09-09 17:55 UTC, jessicaschilling requested changes
Few minor text changes but otherwise LGTM 😊

2020-09-09 17:55 UTC, jessicaschilling commented on ipfs-pinning-service.yaml
> +### Replacing existing pin object
```suggestion
### Replacing an existing pin object
```

2020-09-09 17:55 UTC, jessicaschilling commented on ipfs-pinning-service.yaml
> +The user can replace an existing pin object via `POST /pins/{id}`. This is an atomic shortcut for removing pin object identified by `id` and creating a new one in a single API call. The new pin objec
```suggestion
The user can replace an existing pin object via `POST /pins/{id}`. This is a shortcut for removing a pin object identified by `id` and creating a new one in a single API call. The new pin object `id` is returned in the `PinStatus` response. The old pin object is deleted automatically.
```

2020-09-09 17:55 UTC, jessicaschilling commented on ipfs-pinning-service.yaml
> +      description: Replace an existing pin object; atomic shortcut for executing remove and add
```suggestion
      description: Replace an existing pin object (shortcut for executing both remove and add in one step)
```

2020-09-10 11:15 UTC, andrew approved these changes
Is it worth explaining _why_ a client would want to replace (unless it is just to reduce 2 api calls to 1), the pin update http api docs also fail to explain why it's a thing (I believe it's much more efficient to use update when recursive pins are involved?)

2020-09-10 12:04 UTC, lidel commented
@andrew good point! 

Added notes about protecting against undersired garbage collection of data common to both old and new pin in a3db8e1

2020-09-10 14:10 UTC, jessicaschilling approved these changes

2020-09-10 15:00 UTC, jacobheun approved these changes

2020-09-10 18:17 UTC, andrew approved these changes
👌

2020-09-11 18:30 UTC, lidel commented
This is also a docs-only change, so merging

2020-09-11 18:30 UTC, merged